# MySQLの接続設定（XAMPP用）
spring.datasource.url=jdbc:mysql://localhost:3306/traveldb?useSSL=false&serverTimezone=Asia/Tokyo&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
# XAMPPはデフォルトでパスワードがないので、ここはこのまま（空）でOKです
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#------------------デバッグ用こっちを表示させるときは下のデバッグをグレーアウト
# JPAの設定（テーブルを自動作成・更新させる）
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



#/------------------デバッグ用
# 1. 起動時にテーブルを一度削除して、新しく作り直す設定
#spring.jpa.hibernate.ddl-auto=create

# 2. 実行されるSQLをコンソールで見えるようにする（確認用）
#spring.jpa.show-sql=true

# 3. MySQLの最新のルールを適用する
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect